### all shoppinglists
GET http://localhost:3000/shoppinglists

### create a new shoppinglist
POST http://localhost:3000/shoppinglists
Content-Type: application/json

{ "title": "Neomonde" }

### get one shoppinglist by id
GET http://localhost:3000/shoppinglists/65d0fa81824c475921e9d192

### test get one shoppinglist with an object id not in the db (right length), just doesn't exist)
GET http://localhost:3000/shoppinglists/65c6d6f452572e50cbf9f1e6

### test get one shoppinglist with an invalid object id (not the right length)
GET http://localhost:3000/shoppinglists/whatever

### TODO: update one shoppinglist
PATCH http://localhost:3000/shoppinglists/65d0fa81824c475921e9d192
Content-Type: application/json

{ "title": "Neomonde Med Deli"
}

### add items
POST http://localhost:3000/shoppinglists/65d0fa81824c475921e9d192/items
Content-Type: application/json

{ 
"name": "Baklava",
"purchased": false
}

### TODO: delete one shoppinglist 
DELETE http://localhost:3000/shoppinglists/65cc08ec9119de9b9b226de9


### TODO: update items to be tested
PATCH http://localhost:3000/shoppinglists/65d0fa81824c475921e9d192/items
Content-Type: application/json

{ 
"name": "Tabouleh",
"purchased": true 
}



### Not working byTitle: get one shoppinglist by title 
GET http://localhost:3000/shoppinglists/Costco